# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Example/Podfile
before_install:
- rvm install 2.1.5
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
#- brew update || brew update
#- brew outdated xctool || brew upgrade xctool
script:
- set -o pipefail && xcodebuild test -workspace Example/NADocumentPicker.xcworkspace -scheme NADocumentPicker-Test -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint
